### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by X-nimesh** [senny789/Pagination#3]
![image](https://user-images.githubusercontent.com/48327835/173316004-7b642e87-d950-4dad-8ece-2d734b908cba.png)

why is there a blank page?

**Comment by senny789** [comment]
issue fixed
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/51574734/173317420-a198e025-4542-4ba5-819a-d4c8961b5d6c.png">

**Comment by senny789** [comment]
fixed in 3614c58
